import { Customer } from '../models/customer.interface';

export const CUSTOMERS_TABLE_DATA: Customer[] = [
  {
    id: 1,
    image:
      'https://www.primefaces.org/cdn/primevue/images/landing/apps/avatar2.png',
    active: true,
    name: 'Brook Simmons',
    title: 'Ejecutivo de ventas',
    company: { name: 'Mistranet', logo: 'mistranet' },
    email: 'hi@brooksimmons.co',
    lead: 'Linkedin',
    status: 'Activo',
  },
  {
    id: 2,
    image:
      'https://www.primefaces.org/cdn/primevue/images/landing/apps/avatar9.jpg',
    active: true,
    name: 'Dianne Russell',
    title: 'CEO',
    company: { name: 'BriteMank', logo: 'britemank' },
    email: 'hi@diannerussell.com',
    lead: 'Sitio web',
    status: 'Inactivo',
  },
  {
    id: 3,
    image:
      'https://www.primefaces.org/cdn/primevue/images/landing/apps/avatar13.jpg',
    active: undefined,
    name: 'Amy Elsner',
    title: 'Gerente de producto',
    company: { name: 'ZenTrailMs', logo: 'zentrailms' },
    email: 'hi@amyelsner.com',
    lead: 'Llamada en fr\u00edo',
    status: 'Prospecto',
  },
  {
    id: 4,
    image:
      'https://www.primefaces.org/cdn/primevue/images/landing/apps/avatar11.jpg',
    active: true,
    name: 'Jacob Jones',
    title: 'Gerente',
    company: { name: 'Streamlinz', logo: 'streamlinz' },
    email: 'jacobjones@gmail.com',
    lead: 'Socio',
    status: 'Prospecto',
  },
  {
    id: 5,
    image: '',
    active: false,
    name: 'Cameron Watson',
    capName: 'CW',
    title: 'Gerente de producto',
    company: { name: 'BriteMank', logo: 'britemank' },
    email: 'hi@cameronwatson.com',
    lead: 'Redes sociales',
    status: 'Activo',
  },
  {
    id: 6,
    image: '',
    active: true,
    name: 'Wade Warren',
    capName: 'WW',
    title: 'Director',
    company: { name: 'Streamlinz', logo: 'streamlinz' },
    email: 'hi@wadewarren.com',
    lead: 'Llamada en fr\u00edo',
    status: 'Inactivo',
  },
  {
    id: 7,
    image:
      'https://www.primefaces.org/cdn/primevue/images/landing/apps/avatar7.png',
    active: true,
    name: 'Guy Hawkins',
    title: 'Director',
    company: { name: 'Wavelength', logo: 'wavelength' },
    email: 'hi@guyhawkins.com',
    lead: 'Linkedin',
    status: 'Activo',
  },
  {
    id: 8,
    image:
      'https://www.primefaces.org/cdn/primevue/images/landing/apps/avatar8.png',
    active: true,
    name: 'Annette Black',
    title: 'Gerente',
    company: { name: 'Wavelength', logo: 'wavelength' },
    email: 'annetteblack@wavelength.com',
    lead: 'Sitio web',
    status: 'Inactivo',
  },
  {
    id: 9,
    image:
      'https://www.primefaces.org/cdn/primevue/images/landing/apps/avatar10.jpg',
    active: undefined,
    name: 'Darrell Steward',
    title: 'Gerente de producto',
    company: { name: 'ZenTrailMs', logo: 'zentrailms' },
    email: 'hi@darrellsteward.com',
    lead: 'Sitio web',
    status: 'Activo',
  },
  {
    id: 10,
    image: '',
    active: true,
    name: 'Jerome Bell',
    capName: 'JB',
    title: 'Gerente de marketing',
    company: { name: 'Mistranet', logo: 'mistranet' },
    email: 'hi@jeromebell.com',
    lead: 'Redes sociales',
    status: 'Activo',
  },
  {
    id: 11,
    image:
      'https://www.primefaces.org/cdn/primevue/images/landing/apps/avatar12.jpg',
    active: undefined,
    name: 'Onyama Limba',
    title: 'Ejecutivo de ventas',
    company: { name: 'BriteMank', logo: 'britemank' },
    email: 'hi@onyamalimba.co',
    lead: 'Redes sociales',
    status: 'Activo',
  },
];
