import type { Customer } from '../models/customer.interface';

/**
 * Mock dataset alineado con la vista del sistema legacy: incluye los
 * campos comerciales que el negocio usa para segmentar la cartera —
 * segmento (vertical), clasificación de riesgo, potencial de venta,
 * grupo de descuento y cartera (lifecycle).
 *
 * Mix B2B / B2C ~60/40. RUTs respetan el rango chileno por tipo.
 * Vendedores recurrentes para que el filtro arrayIntersect tenga
 * matches cross-cliente. Distribución intencional de cartera para
 * mostrar las 5 severidades del tag (CA, CP, CN, CI, CM).
 *
 * Distribución de `lifecycle` (ciclo de vida comercial, distinto a
 * `cartera` que es estado financiero): 7 RECURRENTE, 3 INACTIVO,
 * 3 PELIGRO FUGA, 2 FUGADO — cubre las 4 severidades del tag y
 * permite ver casos donde Cartera y Lifecycle divergen (ej. cliente
 * con Cartera=Activa pero Lifecycle=PELIGRO FUGA → paga al día pero
 * compra menos, target de campaña de retención).
 */
export const CUSTOMERS_TABLE_DATA: Customer[] = [
  {
    id: 1,
    type: 'Empresa',
    name: 'Sociedad Comercial Andes Ltda.',
    sortKey: 'Sociedad Comercial Andes Ltda.',
    rut: '76.123.456-7',
    email: 'contacto@andes.cl',
    assignedSellers: ['Carla Méndez', 'Ricardo Toro'],
    availableCredit: 12500000,
    usedCredit: 7500000,
    assignedCredit: 20000000,
    segmento: 'COMERCIO',
    creditClassification: 'A1',
    potencial: 'G1',
    discountGroup: 3,
    cartera: 'CA',
    lifecycle: 'RECURRENTE',
    region: 'Metropolitana de Santiago',
    city: 'SANTIAGO',
  },
  {
    id: 2,
    type: 'Empresa',
    name: 'Industrial Cordillera S.A.',
    sortKey: 'Industrial Cordillera S.A.',
    rut: '96.789.012-3',
    email: 'ventas@cordillera-ind.cl',
    assignedSellers: ['Felipe Ortega'],
    availableCredit: 32000000,
    usedCredit: 18000000,
    assignedCredit: 50000000,
    segmento: 'INDUSTRIAL',
    creditClassification: 'A1',
    potencial: 'G1',
    discountGroup: 4,
    cartera: 'CA',
    lifecycle: 'RECURRENTE',
    region: 'DEL BIOBÍO',
    city: 'CONCEPCIÓN',
  },
  {
    id: 3,
    type: 'Persona',
    name: 'Juan Pablo González Pérez',
    sortKey: 'González',
    rut: '12.345.678-9',
    email: 'jp.gonzalez@gmail.com',
    assignedSellers: ['Carla Méndez'],
    availableCredit: 1800000,
    usedCredit: 1200000,
    assignedCredit: 3000000,
    segmento: 'PASAJEROS',
    creditClassification: 'B1',
    potencial: 'G3',
    discountGroup: 1,
    cartera: 'CA',
    lifecycle: 'RECURRENTE',
    region: 'VALPARAÍSO',
    city: 'VIÑA DEL MAR',
  },
  {
    id: 4,
    type: 'Empresa',
    name: 'Distribuidora Austral Ltda.',
    sortKey: 'Distribuidora Austral Ltda.',
    rut: '78.456.789-0',
    email: 'distribuidora.austral@hotmail.com',
    assignedSellers: ['Macarena Soto', 'Ricardo Toro'],
    availableCredit: 18000000,
    usedCredit: 7000000,
    assignedCredit: 25000000,
    segmento: 'CARGA',
    creditClassification: 'B1',
    potencial: 'G2',
    discountGroup: 2,
    cartera: 'CP',
    lifecycle: 'INACTIVO',
    region: 'DE LOS LAGOS',
    city: 'PUERTO MONTT',
  },
  {
    id: 5,
    type: 'Empresa',
    name: 'Inversiones Patagonia S.A.',
    sortKey: 'Inversiones Patagonia S.A.',
    rut: '96.123.789-K',
    email: 'administracion@patagoniasa.cl',
    assignedSellers: ['Felipe Ortega', 'Macarena Soto'],
    availableCredit: 47500000,
    usedCredit: 12500000,
    assignedCredit: 60000000,
    segmento: 'INDUSTRIAL',
    creditClassification: 'A2',
    potencial: 'G1',
    discountGroup: 5,
    cartera: 'CA',
    lifecycle: 'RECURRENTE',
    region: 'MAGALLANES',
    city: 'PUNTA ARENAS',
  },
  {
    id: 6,
    type: 'Persona',
    name: 'Catalina Andrea Muñoz Salinas',
    sortKey: 'Muñoz',
    rut: '15.678.234-5',
    email: 'cati.munoz@hotmail.com',
    assignedSellers: ['Diego Ramírez'],
    availableCredit: 950000,
    usedCredit: 550000,
    assignedCredit: 1500000,
    segmento: 'PASAJEROS',
    creditClassification: 'B2',
    potencial: 'G3',
    discountGroup: 0,
    cartera: 'CN',
    lifecycle: 'PELIGRO FUGA',
    region: 'COQUIMBO',
    city: 'LA SERENA',
  },
  {
    id: 7,
    type: 'Empresa',
    name: 'Constructora del Norte Ltda.',
    sortKey: 'Constructora del Norte Ltda.',
    rut: '76.567.890-1',
    email: 'contacto@constnorte.cl',
    assignedSellers: ['Carla Méndez', 'Felipe Ortega', 'Diego Ramírez'],
    availableCredit: 35000000,
    usedCredit: 15000000,
    assignedCredit: 50000000,
    segmento: 'CARGA',
    creditClassification: 'A1',
    potencial: 'G1',
    discountGroup: 4,
    cartera: 'CA',
    lifecycle: 'RECURRENTE',
    region: 'ANTOFAGASTA',
    city: 'ANTOFAGASTA',
  },
  {
    id: 8,
    type: 'Persona',
    name: 'Sebastián Andrés Rojas Bravo',
    sortKey: 'Rojas',
    rut: '18.234.567-1',
    email: 's.rojas@yahoo.es',
    assignedSellers: ['Macarena Soto'],
    availableCredit: 0,
    usedCredit: 5000000,
    assignedCredit: 5000000,
    segmento: 'PASAJEROS',
    creditClassification: 'D',
    potencial: 'G4',
    discountGroup: 0,
    cartera: 'CM',
    lifecycle: 'FUGADO',
    region: 'DEL MAULE',
    city: 'TALCA',
  },
  {
    id: 9,
    type: 'Empresa',
    name: 'Servicios Logísticos Atacama Ltda.',
    sortKey: 'Servicios Logísticos Atacama Ltda.',
    rut: '78.890.123-4',
    email: 'ventas@atacamalog.cl',
    assignedSellers: ['Ricardo Toro'],
    availableCredit: 9800000,
    usedCredit: 5200000,
    assignedCredit: 15000000,
    segmento: 'CARGA',
    creditClassification: 'B1',
    potencial: 'G2',
    discountGroup: 2,
    cartera: 'CA',
    lifecycle: 'RECURRENTE',
    region: 'ATACAMA',
    city: 'COPIAPÓ',
  },
  {
    id: 10,
    type: 'Persona',
    name: 'Francisca Paz Vergara Henríquez',
    sortKey: 'Vergara',
    rut: '17.456.789-2',
    email: 'fran.vergara@gmail.com',
    assignedSellers: ['Diego Ramírez', 'Carla Méndez'],
    availableCredit: 3200000,
    usedCredit: 1800000,
    assignedCredit: 5000000,
    segmento: 'COMERCIO',
    creditClassification: 'B2',
    potencial: 'G2',
    discountGroup: 1,
    cartera: 'CA',
    lifecycle: 'INACTIVO',
    region: 'Metropolitana de Santiago',
    city: 'MAIPÚ',
  },
  {
    id: 11,
    type: 'Empresa',
    name: 'Minera del Sur SpA',
    sortKey: 'Minera del Sur SpA',
    rut: '77.678.901-3',
    email: 'contacto@minerasur.cl',
    assignedSellers: ['Felipe Ortega'],
    availableCredit: 50000000,
    usedCredit: 30000000,
    assignedCredit: 80000000,
    segmento: 'INDUSTRIAL',
    creditClassification: 'A1',
    potencial: 'G1',
    discountGroup: 5,
    cartera: 'CA',
    lifecycle: 'RECURRENTE',
    region: 'ANTOFAGASTA',
    city: 'CALAMA',
  },
  {
    id: 12,
    type: 'Persona',
    name: 'Ricardo Eduardo Cárdenas Fuentes',
    sortKey: 'Cárdenas',
    rut: '14.890.234-K',
    email: 'ricardo.cardenas@gmail.com',
    assignedSellers: ['Macarena Soto', 'Diego Ramírez'],
    availableCredit: 5400000,
    usedCredit: 2600000,
    assignedCredit: 8000000,
    segmento: 'COMERCIO',
    creditClassification: 'C1',
    potencial: 'G3',
    discountGroup: 0,
    cartera: 'CP',
    lifecycle: 'PELIGRO FUGA',
    region: 'ÑUBLE',
    city: 'CHILLÁN',
  },
  {
    id: 13,
    type: 'Empresa',
    name: 'Importadora Cisne Blanco SpA',
    sortKey: 'Importadora Cisne Blanco SpA',
    rut: '77.345.901-2',
    email: 'contacto@cisneblanco.cl',
    assignedSellers: ['Ricardo Toro'],
    availableCredit: 6700000,
    usedCredit: 3300000,
    assignedCredit: 10000000,
    segmento: 'COMERCIO',
    creditClassification: 'B2',
    potencial: 'G2',
    discountGroup: 2,
    cartera: 'CA',
    lifecycle: 'INACTIVO',
    region: 'VALPARAÍSO',
    city: 'VALPARAÍSO',
  },
  {
    id: 14,
    type: 'Empresa',
    name: 'Vinos del Valle Central S.A.',
    sortKey: 'Vinos del Valle Central S.A.',
    rut: '96.012.345-7',
    email: 'ventas@vvcentral.cl',
    assignedSellers: ['Carla Méndez'],
    availableCredit: 28000000,
    usedCredit: 12000000,
    assignedCredit: 40000000,
    segmento: 'INDUSTRIAL',
    creditClassification: 'A2',
    potencial: 'G1',
    discountGroup: 4,
    cartera: 'CA',
    lifecycle: 'PELIGRO FUGA',
    region: "DEL LIBERTADOR GRAL. BERNARDO O'HIGGINS",
    city: 'SANTA CRUZ',
  },
  {
    id: 15,
    type: 'Persona',
    name: 'María Antonia Pérez Lagos',
    sortKey: 'Pérez',
    rut: '13.567.890-4',
    email: 'maria.perez.lagos@hotmail.com',
    assignedSellers: ['Felipe Ortega', 'Diego Ramírez'],
    availableCredit: 1650000,
    usedCredit: 1350000,
    assignedCredit: 3000000,
    segmento: 'OTROS',
    creditClassification: 'C2',
    potencial: 'G4',
    discountGroup: 0,
    cartera: 'CI',
    lifecycle: 'FUGADO',
    region: 'ARICA Y PARINACOTA',
    city: 'ARICA',
  },
];
